---
Name: goldfinch-dashpanel-routes
After:
  - '#rootroutes'
  - '#coreroutes'
---

SilverStripe\Control\Director:
  rules:
    'api/dashpanel': Goldfinch\Dashpanel\Controllers\ApiDashpanelController
